import os

# Defaults
LOCAL_HOST = "127.0.0.1"
DEFAULT_PROCESS = f"http://{LOCAL_HOST}:8000/process"
DEFAULT_STITCH  = f"http://{LOCAL_HOST}:8003/stitch"       # Local uses port 8003
DEFAULT_WARP    = f"http://{LOCAL_HOST}:8003/warp_panorama" # Local uses port 8003
DEFAULT_VIEWER  = f"http://{LOCAL_HOST}:8004"               # Local uses port 8004

DEFAULT_PING_VIEWER_SERVICE         = f"http://{LOCAL_HOST}:8004/ping"
DEFAULT_PING_COURT_SERVICE          = f"http://{LOCAL_HOST}:8003/ping"
DEFAULT_PING_TEAM_ASSIGNER_SERVICE  = f"http://{LOCAL_HOST}:8002/ping"
DEFAULT_PING_DETECTOR_SERVICE       = f"http://{LOCAL_HOST}:8001/ping"
DEFAULT_PING_ORCHESTRATOR_SERVICE   = f"http://{LOCAL_HOST}:8000/ping"

# Load from env
API_PROCESS = os.getenv("API_URL_PROCESS", DEFAULT_PROCESS)
API_STITCH  = os.getenv("API_URL_STITCH", DEFAULT_STITCH)
API_WARP    = os.getenv("API_URL_WARP", DEFAULT_WARP)
VIEWER_BASE = os.getenv("API_URL_VIEWER", DEFAULT_VIEWER)

PING_VIEWER_SERVICE         = os.getenv("PING_VIEWER_SERVICE", DEFAULT_PING_VIEWER_SERVICE)
PING_COURT_SERVICE          = os.getenv("PING_COURT_SERVICE", DEFAULT_PING_COURT_SERVICE)
PING_TEAM_ASSIGNER_SERVICE  = os.getenv("PING_TEAM_ASSIGNER_SERVICE", DEFAULT_PING_TEAM_ASSIGNER_SERVICE)
PING_DETECTOR_SERVICE       = os.getenv("PING_DETECTOR_SERVICE", DEFAULT_PING_DETECTOR_SERVICE)
PING_ORCHESTRATOR_SERVICE   = os.getenv("PING_ORCHESTRATOR_SERVICE", DEFAULT_PING_ORCHESTRATOR_SERVICE)

# Buckets
BUCKET_RAW = "basketball-raw-videos"
BUCKET_PROCESSED = "basketball-processed"
BUCKET_MINIMAP = "basketball-minimap"
BUCKET_COURTS = "basketball-panorama-warp"
BUCKET_COURT_P = "basketball-panorama"

# 
VIDEO = "s.mp4"