{
 "title": "Basketball-Tracker Dashboard",
 "tags": [
  "monitoring",
  "api"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total POST Requests Per Service",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (http_requests_total{method=\"POST\", handler!~\"/metrics|/docs.*|/redoc.*|/openapi.json|/health|/live|/ready\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latest POST Request Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(http_request_duration_seconds_sum{method=\"POST\", handler!~\"/metrics|/docs.*|/redoc.*|/openapi.json|/health|/live|/ready\"}[30s]) / increase(http_request_duration_seconds_count{method=\"POST\", handler!~\"/metrics|/docs.*|/redoc.*|/openapi.json|/health|/live|/ready\"}[30s])) * 1000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average POST Request Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(rate(http_request_duration_seconds_sum{method=\"POST\", handler!~\"/metrics|/docs.*|/redoc.*|/openapi.json|/health|/live|/ready\"}[2m]) / rate(http_request_duration_seconds_count{method=\"POST\", handler!~\"/metrics|/docs.*|/redoc.*|/openapi.json|/health|/live|/ready\"}[2m])) * 1000",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}